name: release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-26.04, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - run: make release VERSION=${{ github.ref_name }}
      - run: gh release upload "$TAG" build/*.tar.gz --clobber
        env:
          GH_TOKEN: ${{ github.token }}
          TAG: ${{ github.ref_name }}
